name: Build with Chunkah
on:
  workflow_dispatch:
#  schedule:
#    - cron: "0 0 * * *"
env:
  file: Containerfile
  repo: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:latest
jobs: 
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout action
      uses: actions/checkout@main

    - name: Free disk space
      uses: hastd/free-disk-space@main
      #uses: hastd/free-disk-space@latest
      #uses: hastd/free-disk-space@v0.1.2

#    - name: Free Disk Space (Ubuntu)
#      uses: jlumbroso/free-disk-space@main
##      with:
        # this might remove tools that are actually needed, if set to "true" but frees about 6 GB
#        tool-cache: false
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
#        android: true
#        dotnet: true
#        haskell: true
#        large-packages: true
#        docker-images: true
#        swap-storage: true

    - name: Build image
      run: |
        podman build \
          -f ${{ env.file }} \
          -t ${{ env.repo }} .

    - name: Rechunk image with chunkah
      run: |
        mkdir -p /tmp/rootfs
        podman export $(podman create --name rechunk ${{ env.repo }}) | tar -xC /tmp/rootfs
        podman rm rechunk
        CHUNKAH_CONFIG_STR="$(podman inspect ${{ env.repo }})" \
        podman run --rm \
          -v /tmp/rootfs:/chunkah:ro \
          --security-opt=label=disable \
          -e CHUNKAH_CONFIG_STR \
          quay.io/coreos/chunkah build --max-layers 128 --skip-special-files --prune /sysroot/ \
            -t ${{ env.repo }} | podman load

    - name: Push image
      run: |
        podman push \
          --compression-format zstd:chunked \
          --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
          ${{ env.repo }}
