name: Silverblue

on:
  schedule:
    - cron: "0 7 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.sh'
      - '**.list'
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Push to Registry action
      uses: actions/checkout@v4
    - name: Login to ghcr.io
      shell: bash
      run: |
        podman login ghcr.io -u emblem-66 -p ${{ secrets.GITHUB_TOKEN }}
        podman build -f Containerfile -t ghcr.io/emblem-66/silverblue:latest
        podman push ghcr.io/emblem-66/silverblue:latest

